import { Brand } from "@/types/brand";

const brandData: Brand[] = [
  // {
  //   id: 0.25,
  //   name: "Client",
  //   href: "#",
  //   image: "/images/brand/brand-light-01.svg",
  //   imageLight: "/images/brand/brand-dark-01.svg",
  // },
  // {
  //   id: 0.3,
  //   name: "Client",
  //   href: "#",
  //   image: "/images/brand/brand-light-02.svg",
  //   imageLight: "/images/brand/brand-dark-02.svg",
  // },
  // {
  //   id: 0.4,
  //   name: "Client",
  //   href: "#",
  //   image: "/images/brand/brand-light-03.svg",
  //   imageLight: "/images/brand/brand-dark-03.svg",
  // },
  // {
  //   id: 0.5,
  //   name: "Client",
  //   href: "#",
  //   image: "/images/brand/brand-light-04.svg",
  //   imageLight: "/images/brand/brand-dark-04.svg",
  // },
  // {
  //   id: 0.6,
  //   name: "Client",
  //   href: "#",
  //   image: "/images/brand/brand-light-05.svg",
  //   imageLight: "/images/brand/brand-dark-05.svg",
  // },
  // {
  //   id: 0.7,
  //   name: "Client",
  //   href: "#",
  //   image: "/images/brand/brand-light-06.svg",
  //   imageLight: "/images/brand/brand-dark-06.svg",
  // },
  {
    id: 0.25,
    name: "Client",
    href: "#",
    image: "/images/brand/new/neo4j.png",
    imageLight: "/images/brand/new/neo4j.png",
  },
  {
    id: 0.3,
    name: "Client",
    href: "#",
    image: "/images/brand/new/atlassian.png",
    imageLight: "/images/brand/new/atlassian.png",
  },
  {
    id: 0.4,
    name: "Client",
    href: "#",
    image: "/images/brand/new/buildspace.png",
    imageLight: "/images/brand/new/buildspace.png",
  },
  {
    id: 0.5,
    name: "Client",
    href: "#",
    image: "/images/brand/new/digiocean.png",
    imageLight: "/images/brand/new/digiocean.png",
  },
  {
    id: 0.6,
    name: "Client",
    href: "#",
    image: "/images/brand/new/aws.png",
    imageLight: "/images/brand/new/aws.png",
  },
  {
    id: 0.7,
    name: "Client",
    href: "#",
    image: "/images/brand/new/msme.png",
    imageLight: "/images/brand/new/msme.png",
  },
  {
    id: 0.65,
    name: "Client",
    href: "#",
    image: "/images/brand/new/msft.png",
    imageLight: "/images/brand/new/msft.png",
  },
  {
    id: 0.8,
    name: "Client",
    href: "#",
    image: "/images/brand/new/dpiit.png",
    imageLight: "/images/brand/new/dpiit.png",
  },
  {
    id: 0.85,
    name: "Client",
    href: "#",
    image: "/images/brand/new/google.png",
    imageLight: "/images/brand/new/google.png",
  },
  {
    id: 0.9,
    name: "Client",
    href: "#",
    image: "/images/brand/new/hatch.svg",
    imageLight: "/images/brand/new/hatch.svg",
  },
];

export default brandData;
